services:
  - type: web
    name: n8n-on-render
    env: docker
    plan: free
    repo: https://github.com/Datbwoyyy/n8n
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: 8thGod
      - key: N8N_BASIC_AUTH_PASSWORD
        value: 123Kelly123?
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: "5678"
